name: lint

on:
  pull_request:
  push:
    branches: [main]
  merge_group:

jobs:
  pre-commit:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: setup nix
        uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/43862987c3cf2554a542c6dd81f5f37435eb1423.tar.gz # keep in sync with shell.nix

      - run: df -h

      - name: dry-run nix-shell
        run: nix-shell --pure --run "true"

      - run: df -h

      - name: install dependencies
        run: nix-shell --pure --run "./packaging/install_dependencies.sh"

      - name: cache pre-commit env
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: ${{ matrix.os }}-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: run pre-commit
        run: nix-shell --pure --run "pre-commit run --show-diff-on-failure --color=always --all-files"
